import type { Metadata } from "next";
import { Geist_Mono, Inter, Outfit } from "next/font/google";
import ButtonClickTracker from "@/app/components/ButtonClickTracker";
import "./globals.css";

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfitDisplay = Outfit({
  variable: "--font-display",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google tag (gtag.js) */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-FEWPRZQBH9"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FEWPRZQBH9');
`,
          }}
        />
      </head>
      <body
        className={`${interSans.variable} ${geistMono.variable} ${outfitDisplay.variable} antialiased`}
      >
        <ButtonClickTracker />
        {children}
      </body>
    </html>
  );
}
